# Generated by Django 5.1 on 2025-01-06 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('description', models.CharField(help_text='Просто описание', max_length=400, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('image', models.ImageField(upload_to='images/', verbose_name='выберите велосипед')),
                ('proteins', models.FloatField(verbose_name='Белки (г)')),
                ('fats', models.FloatField(verbose_name='Жиры (г)')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы (г)')),
                ('calories', models.FloatField(verbose_name='Ккал')),
                ('weight', models.FloatField(verbose_name='Вес (г)')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.PROTECT, to='foods.category', verbose_name='категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еды',
            },
        ),
    ]
