# Generated by Django 5.1 on 2025-01-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='выберите изобрежение'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.FloatField(default=12, verbose_name='Вес (г)'),
        ),
    ]
