# Generated by Django 5.1 on 2025-01-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_food_category_alter_food_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.CharField(max_length=50, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.CharField(max_length=50, verbose_name='Углеводы (г)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.CharField(max_length=50, verbose_name='Жиры (г)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.CharField(max_length=50, verbose_name='Белки (г)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.CharField(max_length=50, verbose_name='Вес (г)'),
        ),
    ]
