# Generated by Django 5.1 on 2025-01-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_calories_alter_food_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=1, help_text='Выберите категорию', on_delete=django.db.models.deletion.PROTECT, to='foods.category', verbose_name='категория'),
            preserve_default=False,
        ),
    ]
