# Generated by Django 5.1 on 2025-01-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
