# Generated by Django 5.1 on 2025-01-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_remove_cartitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=10, verbose_name='Тип доставки')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('address_house', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дом')),
                ('address_apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира/офис')),
                ('address_floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('payment_method', models.CharField(choices=[('online', 'Оплата онлайн'), ('card', 'Курьеру картой'), ('cash', 'Наличные')], max_length=10, verbose_name='Метод оплаты')),
                ('delivery_time', models.CharField(choices=[('soon', 'В ближайшее время'), ('time', 'Ко времени')], max_length=10, verbose_name='Время доставки')),
                ('specific_time', models.TimeField(blank=True, null=True, verbose_name='Указанное время')),
                ('person_count', models.PositiveIntegerField(default=1, verbose_name='Количество персон')),
                ('callback_needed', models.BooleanField(default=False, verbose_name='Нужен звонок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
