# Generated by Django 5.1 on 2025-01-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
    ]
